### ISSUE TITLE
KeyError when running example "Upload to Snowflake” Script

### ISSUE THREAD

**Issue by franzbewerunge** [sfc-gh-madkins/feast-snowflake#2]
**Issue**
When I run this script...

```
from feast_snowflake.snowflake_utils import (
    create_new_snowflake_table,
    get_snowflake_conn,
)
from snowflake.connector.pandas_tools import write_pandas
from feast import FeatureStore
import pandas as pd

fs = FeatureStore(repo_path=".")
with get_snowflake_conn(fs.config.offline_store) as conn:

    create_new_snowflake_table(
        conn,
  [...]

```
... to upload random data into snowflake I receive:
```
raise KeyError(key)
KeyError: 'connections.feast_offline_store'
```
Pointing at the config parser [here](https://github.com/sfc-gh-madkins/feast-snowflake/blob/master/feast_snowflake/snowflake_utils.py#L336).

When I look into the `fs.config.offline_store` dict handled by this context manager `with get_snowflake_conn(fs.config.offline_store) as conn:` I clearly see that the creds from the yaml are there and look fine. I do not understand where that key is missing or whether this is a bug or an issue on my end.

Thanks for any help :-)

**Comment by sfc-gh-madkins** [comment]
I had added the ability for the connector to look for the login creds in a config file first then the yaml file. If someone didnt have a config file, it throws an error. This should be fixed now.

**Comment by sfc-gh-madkins** [comment]
See commit 

https://github.com/sfc-gh-madkins/feast-snowflake/commit/f5e5e8d47b972c09584850278dcf057d565c084e
